### ISSUE TITLE
Публикация релизов

### ISSUE THREAD

**Issue by Alexfilus** [philippranzhin/peredelanoconf#13]
Предлагаю при запуске нового события публиковать новый релиз, чтобы те кто подписан, получали уведомления от гитхаба

**Comment by Alexfilus** [comment]
https://github.com/philippranzhin/peredelanoconf/blob/main/locations/opened.md
Тут просто список в файлике, а я предлагаю при анонсе нового мероприятия делать гитхабовский релиз (кажется через теги делается). И там можно текстовое описание задать. 
Кратко: Страна, город, дата, ссылки на ноушн, ссылка на чат в телеге.

**Comment by Alexfilus** [comment]
<img width="334" alt="image" src="https://github.com/philippranzhin/peredelanoconf/assets/5503051/ebc4d02f-d37d-4cc4-8ef6-79340d89774b">
В блоке справа релиз создаётся

**Comment by philippranzhin** [comment]
Круто, попробуем!
