### ISSUE TITLE
Болгария

### ISSUE THREAD

**Issue by Nefariusmag** [philippranzhin/peredelanoconf#131]
Не знаю насколько много переехало в именно в Болгарию, но точно несколько средних международных ИТ компаний перетащило сюда специалистов с семьями, да и на конфах типа JPrime встречал прилично людей.

Хотелось бы понять, если для этого запрос. Чата я пока не видел

**Comment by Alexears** [comment]
Залетай в чатик https://t.me/peredelano_Bulgaria
