### ISSUE TITLE
Ограничение на количество конфы в один день

### ISSUE THREAD

**Issue by proggga** [philippranzhin/peredelanoconf#15]
Нужно решить проблему такого количества конф, понимаю что вы все вытянете но пиар 9 конф в один день не имеет никакого смысла и превратится в шум и мусор, плюс думаю это будет адский хэлл для координаторов ![image](https://github.com/philippranzhin/peredelanoconf/assets/12262156/7d61b159-b0ad-416e-8a00-717760aa80f3)

**Comment by philippranzhin** [comment]
С точки зрения медиаосвещения несколько кофн в день наоборот работают круто — создаётся ощущение что мы повсюду, эффект волны, все дела. По организации да, пиздец тот ещё. Идея в том, что на каждый следующий месяц должно быть больше конф, чем в предыдущий
