### ISSUE TITLE
Добавить в чек-лист оргов аптечку

### ISSUE THREAD

**Issue by koss4ok** [philippranzhin/peredelanoconf#183]
Предлагаю добавить в чеклист для оргов пункт о необходимости собрать экстренную аптечку на всякий случай.

Это отлично, что пока все целы здоровы, но сочетание алкоголя и лестниц/бассейнов могут привести к травмам.
Будет круто, если будет минимальный набор первой помощи.

**Comment by philippranzhin** [comment]
О, а уже есть она

![image](https://github.com/philippranzhin/peredelanoconf/assets/28001927/3312ff19-fae8-4ee0-9e87-b39e1064726f)
