### ISSUE TITLE
Составы всех блюд должны быть подписаны полностью

### ISSUE THREAD

**Issue by veged** [philippranzhin/peredelanoconf#21]
Кроме веганства есть ещё куча разных диетических ограничений и сильно проще прочитать про состав самому, чем узнавать, что, например, в соусе нет того конкретного ореха, на который у тебя аллергия. (Отдельным тикетом могло бы быть пожелание не заправлять еду соусом заранее.)

**Comment by philippranzhin** [comment]
Думаю слишком большая нагрузка на оргов (в каждой стране меню своё), при этом мы вполне можем заранее запрашивать у гостей их ограничения, и вот если они есть — в таком случае уже конкретизировать все блюда с учётом их диет

Как думаешь?

**Comment by veged** [comment]
я думаю, что как раз просто всегда писать все составы и базово заботиться о разнообразии/кастомизации, сильно проще, чем устраивать сбор информации (это ж надо спросить, получить ответ, чтобы никто не забыл про себя написать, может кто-то позже присоединится и т.д. и т.п.) и потом как-то пытаться ещё эту информацию учесть
