### ISSUE TITLE
Добавить ссылку на дискорд/телеграм чатик везде

### ISSUE THREAD

**Issue by dimatakoy** [philippranzhin/peredelanoconf#25]
Я захотел залететь в некоторые чатики конфы, но ни в этом репе, ни на сайте нет ссылок. Мне теперь в твиттере искать их? ;-D

**Comment by envyvox** [comment]
Вот же все лежит https://github.com/philippranzhin/peredelanoconf/blob/main/locations/opened.md

**Comment by dimatakoy** [comment]
Я про ссылки сообщества переделано, а не ссылки на сообществ ближайших конф.

**Comment by envyvox** [comment]
> в некоторые чатики конфы

Ну так ты написал про конфы, я тебе скинул про конфы.
Ссылки на все остальное можно взять отсюда - https://github.com/openworld-community.

**Comment by philippranzhin** [comment]
В /locations лежат все чаты сообществ
