### ISSUE TITLE
Peredelanoconf Serbia

### ISSUE THREAD

**Issue by fenrisis** [philippranzhin/peredelanoconf#31]
Привет уже не первый раз ты пишешь о том что неплохо было бы расширятся в несколько городов если это возможно. Я не знаю насколько кейс с Астаной/Алматы удачный но у нас  Сербии прослеживается такая динамика, есть некий Белградский костяк человек 20-30 а всего в чате  около 650 человек. И весь движ по сути происходит вокруг них, и это наверное не плохо, он хоть какой-то есть. Но не раз было такое что договаривалсь встретится в Нови Саде и приходили только люди которые живут в НС хотя люди из Белграда отмечались но потом как то друг с другом словились и никуда не поехали. Возможно если будет желание у людей живуших в других городах Сербии, сделать несколько митапов в двух городах. Тем более ты говорил что в Сербии был солд-аут.

**Comment by nahuka3** [comment]
Думаю это хорошая идея) Вопрос только — в каких городах Сербии пробовать?) Первая конфа была, по факту, в Нови-Саде, вторая — в Белграде, куда дальше? :)

**Comment by fenrisis** [comment]
> Думаю это хорошая идея) Вопрос только — в каких городах Сербии пробовать?) Первая конфа была, по факту, в Нови-Саде, вторая — в Белграде, куда дальше? :)

Однозначно нужно сделать так чтобы проголосовали участники Сербского комюнити.
Но как сделать так чтобы больше людей увидили это голосование?
Возможо так же живое обсуждение на конфе 12 августа.

**Comment by fenrisis** [comment]
Мне на ум приходят 
-Белград 
-Нови Сад 
-Суботица

**Comment by nahuka3** [comment]
По крайней мере чаты — давайте заведем. @Alexears создай чаты плиз.

**Comment by philippranzhin** [comment]
Завели чатики
