### ISSUE TITLE
Ссылки в телегу, а должны вести на регистрацию

### ISSUE THREAD

**Issue by AndrewShchetkin** [philippranzhin/peredelanoconf#43]
На странице открытых регистраций [locations/opened.md](https://github.com/philippranzhin/peredelanoconf/blob/main/locations/opened.md?plain=1) ссылки ведут в телеграм, логичней сделать ссылки на страницу регистрации

**Comment by philippranzhin** [comment]
Мы хотим, чтобы они вели на страницы в гитхабе же, как сейчас с Ташкентом и Тбилиси

А остальные считай легаси
