### ISSUE TITLE
You can sleep there? I start thinking about breakfast

### ISSUE THREAD

**Issue by proggga** [philippranzhin/peredelanoconf#8]
Раз ночуете и трансфер, то уже захочется и завтрак, яишница там, и бутеры на утро, круто добавить как пункт

https://github.com/philippranzhin/peredelanoconf/blame/6824ea682bf7cc07bd5dcd957f5c8a0f067819ea/confs/standard.md#L32

**Comment by philippranzhin** [comment]
валяй мёрж реквест!

**Comment by proggga** [comment]
сча сделаю, но же не орг, накидываю идеи а вам делать, так что нужно конретно что будем делать, завтрак, повар с завтраком, опционально\доплата или еще как, шведский стол

**Comment by KaterinaPetrova** [comment]
На второй конфе на Кипре в кэмпинге были клаб-сендвичи на завтрак 🥰 Всем очень понравилось, продукты для завтрака точно надо добавить в чек-лист!

**Comment by mrfeod** [comment]
Ди и пиво на утро всегда остаётся!
